language: minimal

sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose-build.yml build
  - docker tag python_build vsuzdaltsev/python_build:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/python_build:latest
