version: '2'
services:
  python_build:
    container_name: python_build
    image: python_build
    entrypoint: ['/bin/sh', '-c', 'while true; do sleep 10; done']
    working_dir: /opt/build
    build:
      context: .
      dockerfile: Dockerfile
